version: '3.9'

services:
  web:
    image: nginx:alpine
    container_name: tinyweather-web
    ports:
      - '8080:80'
    volumes:
      - ./build:/usr/share/nginx/html:ro
    restart: unless-stopped
