services:
  tinyweather:
    image: nginx:alpine
    container_name: tinyweather
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - staging-tunnel
networks:
  staging-tunnel:
    external: true
